// Maps team names (Hebrew + English, including football-data.org variants) to ISO codes for flagcdn.com.
const NAME_TO_ISO = {
  // Hebrew names
  ברזיל: 'br',
  ארגנטינה: 'ar',
  צרפת: 'fr',
  אנגליה: 'gb-eng',
  ספרד: 'es',
  גרמניה: 'de',
  פורטוגל: 'pt',
  הולנד: 'nl',
  מקסיקו: 'mx',
  קנדה: 'ca',
  'ארה"ב': 'us',
  אורוגוואי: 'uy',
  בלגיה: 'be',
  קרואטיה: 'hr',
  קרואטית: 'hr',
  איטליה: 'it',
  יפן: 'jp',
  קוריאה: 'kr',
  'קוריאה הדרומית': 'kr',
  מרוקו: 'ma',
  סנגל: 'sn',
  קמרון: 'cm',
  גאנה: 'gh',
  מצרים: 'eg',
  ניגריה: 'ng',
  'חוף השנהב': 'ci',
  דרום אפריקה: 'za',
  קונגו: 'cd',
  אוסטרליה: 'au',
  איראן: 'ir',
  'ערב הסעודית': 'sa',
  אוזבקיסטן: 'uz',
  ירדן: 'jo',
  'ניו זילנד': 'nz',
  קולומביה: 'co',
  אקוודור: 'ec',
  פרגוואי: 'py',
  "צ'ילה": 'cl',
  פרו: 'pe',
  שוויץ: 'ch',
  שוויצריה: 'ch',
  פולין: 'pl',
  סרביה: 'rs',
  דנמרק: 'dk',
  אוסטריה: 'at',
  סקוטלנד: 'gb-sct',
  הונגריה: 'hu',
  סלובקיה: 'sk',
  סלובניה: 'si',
  אוקראינה: 'ua',
  טורקיה: 'tr',
  גאורגיה: 'ge',
  אלבניה: 'al',
  פנמה: 'pa',
  קוסטה ריקה: 'cr',
  "ג'מייקה": 'jm',
  הונדורס: 'hn',
  וונצואלה: 've',

  // English names (football-data.org uses these)
  Brazil: 'br',
  Argentina: 'ar',
  France: 'fr',
  England: 'gb-eng',
  Spain: 'es',
  Germany: 'de',
  Portugal: 'pt',
  Netherlands: 'nl',
  Mexico: 'mx',
  Canada: 'ca',
  USA: 'us',
  'United States': 'us',
  Uruguay: 'uy',
  Belgium: 'be',
  Croatia: 'hr',
  Italy: 'it',
  Japan: 'jp',
  'Korea Republic': 'kr',
  'South Korea': 'kr',
  Morocco: 'ma',
  Senegal: 'sn',
  Cameroon: 'cm',
  Ghana: 'gh',
  Egypt: 'eg',
  Nigeria: 'ng',
  "Côte d'Ivoire": 'ci',
  'Ivory Coast': 'ci',
  'South Africa': 'za',
  'DR Congo': 'cd',
  Australia: 'au',
  Iran: 'ir',
  'Saudi Arabia': 'sa',
  Uzbekistan: 'uz',
  Jordan: 'jo',
  'New Zealand': 'nz',
  Colombia: 'co',
  Ecuador: 'ec',
  Paraguay: 'py',
  Chile: 'cl',
  Peru: 'pe',
  Switzerland: 'ch',
  Poland: 'pl',
  Serbia: 'rs',
  Denmark: 'dk',
  Austria: 'at',
  Scotland: 'gb-sct',
  Hungary: 'hu',
  Slovakia: 'sk',
  Slovenia: 'si',
  Ukraine: 'ua',
  Turkey: 'tr',
  Türkiye: 'tr',
  Georgia: 'ge',
  Albania: 'al',
  Panama: 'pa',
  'Costa Rica': 'cr',
  Jamaica: 'jm',
  Honduras: 'hn',
  Venezuela: 've',
  Wales: 'gb-wls',
  'Czech Republic': 'cz',
  Czechia: 'cz',
  Romania: 'ro',
  Greece: 'gr',
  Sweden: 'se',
  Norway: 'no',
  Finland: 'fi',
  Ireland: 'ie',
  'Northern Ireland': 'gb-nir',
  Iceland: 'is',
  Bosnia: 'ba',
  'Bosnia and Herzegovina': 'ba',
  'North Macedonia': 'mk',
  Kosovo: 'xk',
  Montenegro: 'me',
  Luxembourg: 'lu',
  Belarus: 'by',
  Qatar: 'qa',
  Iraq: 'iq',
  Bahrain: 'bh',
  Kuwait: 'kw',
  Oman: 'om',
  Yemen: 'ye',
  Syria: 'sy',
  Lebanon: 'lb',
  Palestine: 'ps',
  China: 'cn',
  India: 'in',
  Thailand: 'th',
  Indonesia: 'id',
  Vietnam: 'vn',
  Philippines: 'ph',
  Malaysia: 'my',
  Singapore: 'sg',
  Algeria: 'dz',
  Tunisia: 'tn',
  Libya: 'ly',
  Kenya: 'ke',
  Tanzania: 'tz',
  Uganda: 'ug',
  Zimbabwe: 'zw',
  Zambia: 'zm',
  Angola: 'ao',
  Mozambique: 'mz',
  Ethiopia: 'et',
  Sudan: 'sd',
  Mali: 'ml',
  Burkina: 'bf',
  'Burkina Faso': 'bf',
  Guinea: 'gn',
  Benin: 'bj',
  Togo: 'tg',
  'Cape Verde': 'cv',
  Comoros: 'km',
  Gambia: 'gm',
  Bolivia: 'bo',
  Cuba: 'cu',
  Haiti: 'ht',
  Guatemala: 'gt',
  'El Salvador': 'sv',
  Nicaragua: 'ni',
  Trinidad: 'tt',
  'Trinidad and Tobago': 'tt',
  Curaçao: 'cw',
}

export function isoForTeam(name) {
  if (!name) return null
  const trimmed = name.trim()
  return NAME_TO_ISO[trimmed] ?? NAME_TO_ISO[trimmed.toLowerCase()] ?? null
}
